service: king-of-the-cloud-project
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role: arn:aws:iam::262576497644:role/LabRole

functions:
  getProducts:
    handler: src/functions/products/get.handler
    events:
      - httpApi:
          path: /products
          method: get
  createUser:
    handler: src/functions/users/post.handler
    events:
      - httpApi:
          path: /users
          method: post
